import "@/styles/globals.css";
import type { Metadata } from "next";
import { Providers } from "@/lib/Providers";
import { cn } from "@/lib/utils/cn";
import QueryProvider from "@/lib/trpc/queryProvider";
import { RouterOutputs } from "@/lib/trpc/rsc";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

export type UserMe = RouterOutputs["authRouter"]["me"];

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <QueryProvider>
          <Providers>
            <main
              className={cn(
                // inter.className,
                "min-w-screen min-h-screen bg-background text-foreground light",
              )}
            >
              {children}
              <ToastContainer />
            </main>
          </Providers>
        </QueryProvider>
      </body>
    </html>
  );
}
