import "@/styles/globals.css";
import type { Metadata } from "next";
import Navbar from "@/components/Navbar";
import { useAuth } from "@/lib/store/rsc/auth";
import { redirect } from "next/navigation";
import { RouterOutputs } from "@/lib/trpc/rsc";

type User = RouterOutputs["authRouter"]["me"];

export const metadata: Metadata = {
  title: "SRMap",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: any;
}) {
  const { getState } = await useAuth();
  const { user } = getState();
  if (!user) {
    redirect("/");
  }

  return (
    <Render user={user} {...params}>
      {children}
    </Render>
  );
}

type RenderProps = {
  children: React.ReactNode;
  user: User;
};
const Render = (props: RenderProps) => {
  return (
    <>
      <Navbar></Navbar>
      <>{props.children}</>
    </>
  );
};
